version: '3'

networks:
    angular:

services:
    nginx-angular:
        image: nginx:stable-alpine
        container_name: nginx-angular
        ports:
            - "8088:80"
        volumes:
            - ./dist:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - angular
